version: "3"
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    container_name: "dojo-postgres"
    ports:
      - "5433:5432"
  flyway:
    container_name: "dojo-flyway"
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=1234
      - FLYWAY_URL=jdbc:postgresql://postgres:5432/postgres
      - FLYWAY_GROUP=true
    image: "flyway/flyway"
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - postgres
  postgres-remote:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    container_name: "smart-postgres-remote"
    ports:
      - "5434:5432"
  flyway-remote:
    container_name: "smart-flyway-remote"
    environment:
      - FLYWAY_USER=postgres
      - FLYWAY_PASSWORD=1234
      - FLYWAY_URL=jdbc:postgresql://postgres-remote:5432/postgres
      - FLYWAY_GROUP=true
    image: "flyway/flyway"
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ./flyway/remote/sql:/flyway/sql
    depends_on:
      - postgres-remote
  ftpd_server:
    image: stilliard/pure-ftpd
    container_name: dojo-ftpd
    ports:
      - "9021:21"
      - "30000-30009:30000-30009"
    volumes:
      - "/tmp/data:/home/username/"
      - "/tmp/passwd:/etc/pure-ftpd/passwd"
    environment:
      PUBLICHOST: "localhost"
      FTP_USER_NAME: user
      FTP_USER_PASS: pass
      FTP_USER_HOME: /home/username
    restart: always