spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver
spring.batch.initialize-schema: always
csv.fileName: feladat_1.csv