spring.batch.initialize-schema: always

datasource:
  jdbc-url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 123456
  driverClassName: org.postgresql.Driver

csv:
  fileName: feladat_1.csv
  fields: last_name,first_name,age